colors:
  rosewater: '8b4d4d'
  flamingo: 'a24040'
  pink: '984080'
  mauve: '7c32a8'
  red: 'b82530'
  maroon: 'a03050'
  peach: 'a85820'
  yellow: '806010'
  green: '287028'
  teal: '207068'
  sky: '1878a8'
  sapphire: '206090'
  blue: '2850a8'
  lavender: '5858a0'

  text: '4c4e5e'
  subtext1: '5a5c6a'
  subtext0: '686a78'
  overlay2: '767885'
  overlay1: '848692'
  overlay0: '92949f'
  surface2: 'a0a2ab'
  surface1: 'afb1b8'
  surface0: 'bdbfc5'
  base: 'f5f7fa'
  mantle: 'e6e9ef'
  crust: 'dce0e8'

core:
  normal_text: {}
  regular_file: {}
  reset_to_normal: {}

  directory:
    foreground: blue

  symlink:
    foreground: pink

  multi_hard_link: {}

  fifo:
    foreground: crust
    background: blue

  socket:
    foreground: crust
    background: pink

  door:
    foreground: crust
    background: pink

  block_device:
    foreground: sapphire
    background: surface0

  character_device:
    foreground: pink
    background: surface0

  broken_symlink:
    foreground: crust
    background: red

  missing_symlink_target:
    foreground: crust
    background: red

  setuid: {}
  setgid: {}
  file_with_capability: {}
  sticky_other_writable: {}
  other_writable: {}
  sticky: {}

  executable_file:
    foreground: red
    font-style: bold

text:
  special:
    foreground: base
    background: yellow

  todo:
    font-style: bold

  licenses:
    foreground: overlay2

  configuration:
    foreground: yellow

  other:
    foreground: yellow

markup:
  foreground: yellow

programming:
  source:
    foreground: green

  tooling:
    foreground: teal

    continuous-integration:
      foreground: green

media:
  foreground: flamingo

office:
  foreground: red

archives:
  foreground: sapphire
  font-style: underline

executable:
  foreground: red
  font-style: bold

unimportant:
  foreground: surface2
