colourful: true

filekinds:
  normal: {foreground: "#4c4e5e"}
  directory: {foreground: "#5858a0"}
  symlink: {foreground: "#2850a8"}
  pipe: {foreground: "#5a5c6a"}
  block_device: {foreground: "#a03050"}
  char_device: {foreground: "#a03050"}
  socket: {foreground: "#5a5c6a"}
  special: {foreground: "#7c32a8"}
  executable: {foreground: "#287028"}
  mount_point: {foreground: "#207068"}

perms:
  user_read: {foreground: "#b82530", is_bold: true}
  user_write: {foreground: "#806010", is_bold: true}
  user_execute_file: {foreground: "#287028", is_bold: true}
  user_execute_other: {foreground: "#287028", is_bold: true}
  group_read: {foreground: "#b82530"}
  group_write: {foreground: "#806010"}
  group_execute: {foreground: "#287028"}
  other_read: {foreground: "#b82530"}
  other_write: {foreground: "#806010"}
  other_execute: {foreground: "#287028"}
  special_user_file: {foreground: "#7c32a8"}
  special_other: {foreground: "#848692"}
  attribute: {foreground: "#767885"}

size:
  major: {foreground: "#686a78"}
  minor: {foreground: "#1878a8"}
  number_byte: {foreground: "#5a5c6a"}
  number_kilo: {foreground: "#686a78"}
  number_mega: {foreground: "#2850a8"}
  number_giga: {foreground: "#7c32a8"}
  number_huge: {foreground: "#7c32a8"}
  unit_byte: {foreground: "#686a78"}
  unit_kilo: {foreground: "#1878a8"}
  unit_mega: {foreground: "#7c32a8"}
  unit_giga: {foreground: "#7c32a8"}
  unit_huge: {foreground: "#207068"}

users:
  user_you: {foreground: "#4c4e5e"}
  user_root: {foreground: "#b82530"}
  user_other: {foreground: "#a03050"}
  group_yours: {foreground: "#686a78"}
  group_other: {foreground: "#767885"}
  group_root: {foreground: "#b82530"}

links:
  normal: {foreground: "#2850a8"}
  multi_link_file: {foreground: "#2850a8"}

git:
  new: {foreground: "#287028"}
  modified: {foreground: "#806010"}
  deleted: {foreground: "#a03050"}
  renamed: {foreground: "#207068"}
  typechange: {foreground: "#984080"}
  ignored: {foreground: "#848692"}
  conflicted: {foreground: "#a85820"}

git_repo:
  branch_main: {foreground: "#686a78"}
  branch_other: {foreground: "#7c32a8"}
  git_clean: {foreground: "#287028"}
  git_dirty: {foreground: "#a03050"}

security_context:
  colon: {foreground: "#92949f"}
  user: {foreground: "#848692"}
  role: {foreground: "#7c32a8"}
  typ: {foreground: "#a0a2ab"}
  range: {foreground: "#7c32a8"}

file_type:
  image: {foreground: "#806010"}
  video: {foreground: "#b82530"}
  music: {foreground: "#287028"}
  lossless: {foreground: "#207068"}
  crypto: {foreground: "#848692"}
  document: {foreground: "#4c4e5e"}
  compressed: {foreground: "#984080"}
  temp: {foreground: "#a03050"}
  compiled: {foreground: "#206090"}
  source: {foreground: "#2850a8"}

punctuation: {foreground: "#92949f"}
date: {foreground: "#806010"}
inode: {foreground: "#686a78"}
blocks: {foreground: "#92949f"}
header: {foreground: "#4c4e5e"}
octal: {foreground: "#207068"}
flags: {foreground: "#7c32a8"}

symlink_path: {foreground: "#1878a8"}
control_char: {foreground: "#206090"}
broken_symlink: {foreground: "#b82530"}
broken_path_overlay: {foreground: "#a0a2ab"}
